import Footer from "../components/Footer";
import Header from "../components/Header"
import "./globals.css";

export const metadata = {
    title: "Din Mægler",
    description: "Generated by create next app",
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
